### PR TITLE
Drop dependency on deprecated gulp-util

### PR DESCRIPTION
**Pull request by grig0ry**
Replace deprecated dependency gulp-util

[`gulp-util`](https://www.npmjs.com/package/gulp-util) has been deprecated recently. Continuing to use this dependency may prevent the use of your library with the recently released version 4 of Gulp, **it is important to replace `gulp-util`**.

The [README.md](https://github.com/gulpjs/gulp-util) lists alternatives for all the components so a simple replacement should be enough.

Your package is popular but still relying on `gulp-util`, it would be good to publish a fixed version to npm as soon as possible.

See:
- https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
- https://github.com/gulpjs/gulp-util/issues/143

### CODE REVIEW

**Comment by grig0ry** [comment]
@olets No problem, fixed.

**Comment by bezoerb** [comment]
@olets: We should have bumped the version in package.json as we can't do this on publish with the protected master branch...

**Comment by bezoerb** [comment]
https://github.com/zimmen/gulp-twig/pull/47

**Comment by olets** [comment]
Yeah I figured that'd be its own PR so that we could talk about closing out some of these other PRs and including them in the release. I don't have strong feelings about it though

**Pull request merged**
