### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by olets**
Updates gulp-util and twig.js

twig.js 0.8.9 adds a number of major improvements over 0.8.6 - [see the changelog](https://github.com/justjohn/twig.js/blob/master/CHANGELOG.md)

### CODE REVIEW

**Comment by olets** [comment]
Updated to twig.js 0.9.1

0.9.0 adds many changes ([changelog](https://github.com/twigjs/twig.js/blob/master/CHANGELOG.md))

**Comment by florianbouvot** [comment]
@zimmen hi, can you take a look at this PR ? Thanks in advance for your work.

**Comment by ryuran** [comment]
@zimmen some news about this PR ?

**Comment by zimmen** [comment]
Sorry guys, I havent been active for a while. I have merged this PR, looking into others as well.

**Comment by ryuran** [comment]
waiting for release 🎉

**Comment by zimmen** [comment]
It should be on npm by now.

Also, see [this](https://github.com/zimmen/gulp-twig/wiki/Looking-for-maintainer-or-collaborator(s)) :-)

**Pull request merged**
