### PR TITLE
Updated twig.js to 0.8.6 and the version number to 0.3.1

### PR DESCRIPTION
**Pull request by JoelSutherland**
I'm using the latest version on a project with no issues.

The tests in the repo error (for me) but it appears to just be a line break issue. The new version is adding '\n' after each line in a way that the test don't like. I'm not sure how to resolve it. I am on Windows so perhaps they would pass without error on unix/OSX.

### CODE REVIEW

**Comment by JoelSutherland** [comment]
Looks like they do pass!

**Comment by implico** [comment]
So, why don't we merge? :) I extremely need the "embed" tag added in the latest twig.js version...

**Comment by JoelSutherland** [comment]
I've been using it with the merge and it works great.

**Comment by zimmen** [comment]
Sorry, I was enjoying some days off but here we go! :-)

**Comment by implico** [comment]
Nice, thanks:)

**Comment by zimmen** [comment]
I did publish it to NPM as version 0.5.0 so you might have to update your dependencies:-)

**Pull request merged**
