### PR TITLE
Add extname option

### PR DESCRIPTION
**Pull request by bezoerb**

### CODE REVIEW

**Comment by dotmagic** [comment]
I'm not really sure we need this feature in gulp-twig? I prefer to use `gulp-rename` in such rare cases since it offers even more features. How do you guys think?

**Comment by bezoerb** [comment]
i think we should not enforce another dependency to choose the extname of the output we're creating.

**Comment by bezoerb** [comment]
And this is already flagged as [next.feature](https://github.com/zimmen/gulp-twig/milestone/1 )

**Comment by dotmagic** [comment]
Well, it's really just a small change. Why not :)
I've noticed `gulp-nunjucks-render` has such a option too. It would be nice if it's possible to omit the extension completely, with `gulp-nunjucks-render` its possible when you pass a empty string or null.

**Comment by dotmagic** [comment]
Thanks, looks fine now. I gonna test & merge it this weekend.

**Comment by bezoerb** [comment]
\o/

**Pull request merged**
