### PR TITLE
Pass through namespaces option

### PR DESCRIPTION
**Pull request by dennisreimann**
See https://github.com/justjohn/twig.js/wiki#namespaces

### CODE REVIEW

**Comment by gravypower** [comment]
+1 to this

**Comment by jameschetwood** [comment]
@zimmen Any progress / thoughts on this? Thanks

**Comment by linnett** [comment]
@zimmen I'm with James here - could this be approved please? We really need to use this feature in production and it would be most helpful! Thanks

**Comment by zimmen** [comment]
Sure, i'll get on it this evening.

**Comment by linnett** [comment]
@zimmen that's great - thank you!

**Comment by jameschetwood** [comment]
@zimmen Thanks a lot! Some documentation would also be great. Ive manually applied the commit while I wait but I can see where to set the namespace.

**Comment by zimmen** [comment]
I'll have to look into this myself first. As i'm not using the namespaces myself at the moment.

**Comment by linnett** [comment]
@zimmen hi - did you manage to take a look at this one? thanks

**Comment by linnett** [comment]
@dennisreimann how did you set namespaces in your gulp task?

**Comment by dennisreimann** [comment]
@linnett just like the other options:

```javascript
.pipe(twig({
    namespaces: {
        a: 'a',
        b: 'b'
    }
}))
```

**Comment by linnett** [comment]
@dennisreimann thanks - will give it a try

**Comment by jameschetwood** [comment]
@dennisreimann Did you have this working? Ive manually applied your path and tried the following (and a few syntax variations) but I cant get it working: 

Old path: 
```
{% include "../button/button.twig" %}
```

New settings and path: 

```
.pipe(plugins.twig({
  namespaces: {
    app: '../button/'
},
```

```
{% include "@App/button.twig" %}
```

**Comment by linnett** [comment]
@zimmen do you know when this will be included and documented?

**Comment by LoicGoyet** [comment]
I do not make it work either :(. My options into the gulp tasks are :
```javascript
.pipe(twig({
  namespaces: {
    styleguide: 'src/templates/ts-components'
  }
}))
```

And then I tried several synthax for an include of the file `src/templates/ts-components/section-header.twig` into the template `src/templates/molecules/callout.twig`.

##### Like into symfony projects :
```twig
{% include '@styleguide/section-header.twig' %}
```

##### Like documented into the [twig.js wiki](https://github.com/twigjs/twig.js/wiki#namespaces) :
```twig
{% include 'styleguide::section-header.twig' %}
```

I also tried into the config to setup the `styleguide` namespace as relative or absolute.

None of thoses tries worked, any ideas ? Thanks a lot

**Comment by LoicGoyet** [comment]
any updates ? :(

**Comment by Floppery** [comment]
Where need options! Please merge this   ##commit!!!

**Comment by zimmen** [comment]
Merged. Along with another PR.

**Comment by linnett** [comment]
Can we have the documentation updated for this please?

**Comment by zimmen** [comment]
It is basically passing it along to twig.js itself. See https://github.com/twigjs/twig.js/wiki#namespaces

I'll put that snippet in the docs as well

**Comment by linnett** [comment]
Thanks - we'll give it a go

**Pull request merged**
